apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cats-app-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames: [default]
  selector:
    matchLabels:
      app: cats
  endpoints:
  - port: web
    path: /metrics
    interval: 15s
    honorLabels: true 