# k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cats-service
spec:
  selector:
    app: cats-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer